export const suppliersPath="/dev-preview/suppliers-services";
export const supplierEntryPath=suppliersPath+"/entry";
export const supplierCategories=["Seeds & Planting Materials","Farm Inputs","Tools & Equipment","Irrigation & Water","Mechanisation","Transport & Logistics","Packaging & Storage","Agricultural Services"] as const;
export type Provider={id:string;name:string;category:string;type:"Supplier"|"Service Provider"|"Both";base:string;baseRegion:string;serves:string[];offerings:string[];about:string;areaState:"Participant-reported"|"Needs confirmation"|"Information under review";};
export type SupplierState={q:string;category:string;region:string;page:number;fixture:string};
export const perPage=6;
const norm=(s:string)=>s.normalize("NFKC").trim().toLocaleLowerCase("en");
export function matchingProviders(items:Provider[],s:SupplierState){return items.filter(p=>(!s.category||p.category===s.category)&&(!s.region||p.serves.includes(s.region))&&norm(s.q).split(/\s+/).filter(Boolean).every(term=>norm([p.name,p.category,p.base,p.baseRegion,...p.serves,...p.offerings].join(" ")).includes(term))).sort((a,b)=>a.name.localeCompare(b.name,"en")||a.id.localeCompare(b.id));}
export function supplierUrl(s:SupplierState){const q=new URLSearchParams();if(s.q)q.set("q",s.q);if(s.category)q.set("category",s.category);if(s.region)q.set("region",s.region);if(s.page>1)q.set("page",String(s.page));if(s.fixture)q.set("fixture",s.fixture);return suppliersPath+(q.size?"?"+q:"");}
export function readSuppliers(q:URLSearchParams,items:Provider[]):SupplierState{const s={q:(q.get("q")||"").normalize("NFKC").trim().slice(0,120),category:q.get("category")||"",region:q.get("region")||"",page:Math.max(1,Math.min(10000,Number.parseInt(q.get("page")||"1",10)||1)),fixture:["empty","unavailable"].includes(q.get("fixture")||"")?q.get("fixture")!:""};if(!supplierCategories.some(c=>c===s.category))s.category="";if(!items.some(p=>p.serves.includes(s.region)))s.region="";s.page=Math.min(s.page,Math.max(1,Math.ceil((s.fixture?0:matchingProviders(items,s).length)/perPage)));return s;}
export function safeSupplierReturn(value:string|undefined,items:Provider[]){if(!value||!value.startsWith(suppliersPath))return suppliersPath;try{const u=new URL(value,"https://preview.invalid");if(u.origin!=="https://preview.invalid"||u.pathname!==suppliersPath)return suppliersPath;const hash=items.some(p=>"#provider-"+p.id===u.hash)?u.hash:"";return supplierUrl(readSuppliers(u.searchParams,items))+hash;}catch{return suppliersPath;}}
export function providerUrl(id:string,from:string){return suppliersPath+"/"+encodeURIComponent(id)+"?from="+encodeURIComponent(from);}
