/** P09-RC1-A1 curated sources. No live retrieval, copied manuals or implied approval. */
export type AgronomySource = {
  id: string; title: string; url: string; geography: string; date: string;
  applicability: "Ghana" | "regional" | "general";
  scope: string; exclusions: string;
};
export const AGRONOMY_CHECKED_ON = "2026-10-01";
export const AGRONOMY_REVIEW = "Not professionally certified; external agronomic/post-harvest certification DEFERRED — PLANNED POST-LAUNCH; not an initial-launch blocker or automatic next gate after founder product-quality approval";
export const agronomySources: AgronomySource[] = [
  { id: "VT-DIAG", title: "Virginia Cooperative Extension: Diagnosing Plant Problems", url: "https://www.pubs.ext.vt.edu/content/dam/pubs_ext_vt_edu/426/426-714/426-714.pdf", geography: "United States; general diagnostic principles", date: "2018", applicability: "general", scope: "Compare root health, moisture, matching pest injury, spread and field-work patterns. Wilting has multiple possible causes; visual clues are not pathogen confirmation.", exclusions: "No Ghana disease prevalence, named crop diagnosis, chemical treatment or ornamental/cold-climate recommendations transferred." },
  { id: "RUTGERS-STAKE", title: "Rutgers NJAES: Tomato training techniques", url: "https://njaes.rutgers.edu/fs678/", geography: "New Jersey, United States; support mechanics only", date: "Page date not stated; checked 2026-10-01", applicability: "general", scope: "Stakes/cages, soft figure-eight ties, room for stem growth and support as plants grow.", exclusions: "No US climate/calendar, numeric spacing, pruning prescription, rates or food-safety statements imported." },
  { id: "FAO-LOWRESOURCE", title: "FAO: Prevention of post-harvest food losses — drying and warehouses", url: "https://www.fao.org/4/x0039e/X0039E04.htm", geography: "General grain handling", date: "Chapter date not stated; checked 2026-10-01", applicability: "general", scope: "Thin-layer sun drying, turning, clean sheet rather than bare soil, rain/night protection and raised bag storage with inspection access.", exclusions: "No pesticides, asbestos construction, numeric moisture/temperature thresholds or safe-storage duration copied from this older manual." },
  { id: "FAO-MAIZE-HANDLING", title: "FAO: A guide to maize marketing — drying and storage", url: "https://www.fao.org/4/x0530e/x0530e05.htm", geography: "African maize marketing examples; not Ghana-specific", date: "Chapter date not stated; checked 2026-10-01", applicability: "regional", scope: "Cob versus shelled maize drying, sheet handling and protection from re-wetting; low-resource storage preparation.", exclusions: "No insecticide recommendation, marketing guarantee, price, numerical drying or safety threshold." },
  { id: "GH-MAIZE", title: "MoFA / DAES: Maize Production Guide", url: "https://www.mofa.gov.gh/site/images/pdf/production_guides/GUIDE_TO_MAIZE_PRODUCTION.pdf", geography: "Ghana", date: "2020", applicability: "Ghana", scope: "Growth stages, drainage, field/input history and maturity versus storage dryness (pp. 3–6, 14, 26–29).", exclusions: "No rates, pesticide products, calendar guarantees, temperature or moisture thresholds imported." },
  { id: "GH-NUTRIENTS", title: "MoFA: New Fertilizer Blends, the way for Ghana", url: "https://mofa.gov.gh/site/media-centre/latest-news/item/555-new-fertilizer-blends-the-way-for-ghana", geography: "Ghana: Forest Savannah Transition and Guinea Savannah", date: "2020 (publication year from indexed page)", applicability: "Ghana", scope: "Recommendations depend on crop and agroecology; blanket colour-based rates are not justified.", exclusions: "Tables of formulations/rates excluded pending local reviewer confirmation." },
  { id: "PSU-PATTERN", title: "Penn State: Diagnosing a Plant Problem 101", url: "https://extension.psu.edu/diagnosing-a-plant-problem-101", geography: "United States; general diagnostic process", date: "2025 (indexed; full page unavailable on check)", applicability: "general", scope: "Onset, spread, distribution and comparison of affected/healthy plants. Pattern is a clue, not proof.", exclusions: "No US disease prevalence or treatment transferred to Ghana. Indexed text only." },
  { id: "PSU-DISORDERS", title: "Penn State: Solving the Case of Crop Disorders", url: "https://extension.psu.edu/solving-the-case-of-crop-disorders-the-role-of-patterns-in-diagnosis", geography: "United States; field diagnostic principles", date: "2024 (indexed)", applicability: "general", scope: "Living and nonliving causes can coexist; matching pest signs, roots, field edges and application patterns help distinguish causes.", exclusions: "No disease confirmation from field pattern alone." },
  { id: "UMN-YELLOW", title: "University of Minnesota: 4 key nutrient deficiencies to scout for early in the season", url: "https://blog-crop-news.extension.umn.edu/2017/05/4-key-nutrient-deficiencies-to-scout.html", geography: "Minnesota, USA", date: "2017-05", applicability: "general", scope: "Maize nitrogen-like V-pattern versus other yellowing patterns; visual signs prompt investigation, not a rate.", exclusions: "No Minnesota rates, season or local incidence transferred." },
  { id: "CABI-TOMATO", title: "Plantwise / KENGAP: Blossom end rot on Tomato", url: "https://factsheetadmin.plantwise.org/Uploads/PDFs/20137804265.pdf", geography: "Kenya; factsheet also lists China", date: "2012-12", applicability: "regional", scope: "Sunken blossom-end damage and uneven moisture as a differential for tomato fruit rot.", exclusions: "No foliar calcium, lime or chemical recommendations imported; no Ghana incidence claim." },
  { id: "UC-WHITEFLY", title: "UC IPM: Whiteflies, Tomato", url: "https://ipm.ucanr.edu/agriculture/tomato/whiteflies/", geography: "California, USA", date: "Not stated in inspected text", applicability: "general", scope: "Adults lift when disturbed; immature stages beneath leaves; honeydew/sooty growth support a sap-feeder possibility.", exclusions: "No species, virus diagnosis, California thresholds or pesticides transferred." },
  { id: "IITA-CASSAVA", title: "IITA: Starting a Cassava Farm, IPM Field Guide", url: "https://www.iita.org/wp-content/uploads/2016/06/Starting_a_cassava_farm.pdf", geography: "Benin, Cameroon, Ghana and Nigeria extension programme", date: "2000; based on 1993–1997 ESCaPP", applicability: "regional", scope: "Healthy stem material, site history, loose soil, drainage and soil-dependent beds/ridges (pp. 6–7, 16–17).", exclusions: "Old pesticide dips, hot-water recipes, spacing and doses excluded." },
  { id: "IITA-YAM", title: "CGIAR / IITA: A machine for making yam mounds?", url: "https://www.cgiar.org/news-events/news/a-machine-for-making-yam-mounds", geography: "West African yam production context", date: "2021 (indexed)", applicability: "regional", scope: "Mounds create loose rooting soil; method and size require soil/species/local validation.", exclusions: "No universal mound height, spacing or yield claim." },
  { id: "FAO-PEPPER", title: "FAO: Hot pepper seed and crop production in the Bahamas, transplanting", url: "https://www.fao.org/4/y5259e/y5259e06.htm", geography: "Bahamas", date: "Not stated on inspected chapter", applicability: "general", scope: "Harden healthy seedlings, prepare moist field, preserve nursery depth, water after transplanting.", exclusions: "No local season, spacing, burn instruction or chemical recommendation transferred." },
  { id: "UMN-STAKE", title: "University of Minnesota: Early season tomato sleuthing", url: "https://extension.umn.edu/about/our-stories/news/yard-and-garden-news/early-season-tomato-sleuthing", geography: "Minnesota, USA", date: "2026 (indexed)", applicability: "general", scope: "Support differs for vining/bush tomatoes; gentle ties and stable support.", exclusions: "No climate/calendar transfer, pruning prescription or yield guarantee." },
  { id: "FAO-GRAIN", title: "FAO: Prevention of post-harvest food losses, stored produce", url: "https://www.fao.org/4/x0039e/x0039e05.htm", geography: "Tropical grain storage, including northern Nigeria examples", date: "Not stated on inspected chapter", applicability: "general", scope: "Dry grain before sealed storage; protect containers from damage, insects and rodents.", exclusions: "No fumigation, chemical treatments, moisture thresholds or food/feed clearance." },
  { id: "FAO-DRY", title: "FAO: Farm structures, Grain drying", url: "https://www.fao.org/4/s1250e/S1250E0v.htm", geography: "Tropical farm structures", date: "Not stated on inspected chapter", applicability: "general", scope: "Air movement and humidity limit drying; a covered wet heap is not dry storage.", exclusions: "No numerical moisture, heat or safe-duration prescription." },
  { id: "FAO-HANDLING", title: "FAO: Small-scale postharvest handling practices, harvesting", url: "https://www.fao.org/4/ae075e/ae075e04.htm", geography: "General horticulture", date: "Chapter cites FAO 1989; edition not verified", applicability: "general", scope: "Gentle harvest, protect against bruising, clean supportive containers, reduce handling.", exclusions: "No shelf-life guarantee, food-safety clearance or processing recipe." },
  { id: "FAO-ROOTS", title: "FAO: Handling and storage methods for fresh roots and tubers", url: "https://www.fao.org/4/x5415e/x5415e04.htm", geography: "Tropics; commodity-specific examples", date: "1998 manual; chapter date not separately stated", applicability: "general", scope: "Cassava deteriorates rapidly; yam, sweet potato and cocoyam differ; avoid damage and do not generalise curing.", exclusions: "Curing conditions, chemical dips, toxicity processing and storage durations excluded." },
  { id: "FAO-CURING", title: "FAO: Small-scale postharvest handling, curing", url: "https://www.fao.org/4/ae075e/ae075e05.htm", geography: "General horticulture", date: "Edition not verified", applicability: "general", scope: "Root wound healing and onion neck/skin drying are different processes.", exclusions: "No numerical curing recipe; requires commodity-specific qualified review." }
];
export function agronomySource(id: string) {
  const source = agronomySources.find((item) => item.id === id);
  if (!source) throw new Error(`Unknown agronomy source: ${id}`);
  return source;
}

// Coverage describes this evidence layer, not whether a name exists in a selector.
export const agronomyCoverage = [
  { crops: ["Maize"], level: "focused crop guidance", topics: ["stage", "yellowing differential", "nutrient decision", "harvest", "drying/storage"], sources: ["GH-MAIZE", "GH-NUTRIENTS", "UMN-YELLOW", "FAO-GRAIN"] },
  { crops: ["Cassava"], level: "focused crop guidance", topics: ["establishment", "poor growth", "roots", "harvest/storage limits"], sources: ["IITA-CASSAVA", "FAO-ROOTS"] },
  { crops: ["Tomato"], level: "focused crop guidance", topics: ["fruit-rot differential", "white insects", "support", "surplus handling"], sources: ["CABI-TOMATO", "UC-WHITEFLY", "UMN-STAKE", "FAO-HANDLING"] },
  { crops: ["Pepper", "Chilli"], level: "focused method guidance", topics: ["nursery-to-field transplant", "general signs", "handling"], sources: ["FAO-PEPPER", "PSU-PATTERN", "FAO-HANDLING"] },
  { crops: ["Okra"], level: "general differential; no Ghana disease ranking", topics: ["dying/wilting", "field pattern", "roots/stems", "white insects"], sources: ["PSU-PATTERN", "PSU-DISORDERS", "UC-WHITEFLY"] },
  { crops: ["Yam"], level: "focused method and handling", topics: ["mounds", "harvest injury", "storage limitations"], sources: ["IITA-YAM", "FAO-ROOTS"] },
  { crops: ["Rice", "Sorghum", "Millet", "Cowpea", "Groundnut", "Soybean", "Bambara groundnut"], level: "general grain/legume storage only", topics: ["dryness", "container integrity", "mould escalation"], sources: ["FAO-GRAIN", "FAO-DRY"] },
  { crops: ["Cocoyam", "Sweet potato"], level: "limited root handling", topics: ["harvest injury", "crop-specific curing referral"], sources: ["FAO-ROOTS", "FAO-CURING"] },
  { crops: ["Onion", "Garden egg", "Cucumber", "Cabbage", "Lettuce", "Carrot"], level: "general diagnostic/handling principles", topics: ["observable signs", "handling", "onion curing distinction"], sources: ["PSU-PATTERN", "FAO-HANDLING", "FAO-CURING"] },
  { crops: ["Plantain", "Banana", "Pineapple", "Mango", "Citrus", "Papaya", "Watermelon", "Avocado"], level: "general diagnostic/handling principles", topics: ["observable signs", "bruising", "handling"], sources: ["PSU-PATTERN", "FAO-HANDLING"] },
  { crops: ["Cocoa", "Oil palm", "Cashew", "Coconut", "Coffee", "Rubber", "Shea"], level: "evidence collection and referral only", topics: ["field pattern", "visible signs", "no new processing protocol"], sources: ["PSU-PATTERN"] }
] as const;

export function agronomyCoverageFor(crop?: string | null) {
  return agronomyCoverage.find((row) => row.crops.some((name) => name.toLowerCase() === crop?.toLowerCase()));
}
