// P09-2: amended P09-0A handoff Â§4; no operational/publication authority implied.
export const homepage = {
  review: "Amended homepage · Protected review",
  boundary: "Structure and surface rhythm approved. Hero, product preview and Route A header/footer are under founder review. No operational readiness or release approval is implied.",
  fixtureNotice: "Synthetic Preview dataset — not real farmers, suppliers or offers. Search and tabs operate only on these test records. No prices, availability, verification or contact details are represented.",
  fixtureLabel: "Synthetic fixture · not a real record",
  fixtureSearch: "Search synthetic Preview profiles by product, name or example region.",
  headline: "Find produce. Find farmers. Farm smarter.",
  actions: ["Buy Produce", "List Your Farm"],
  searchLabel: "Farmers & Suppliers",
  searchHint: "Search by product, farmer or supplier name, or region",
  shortcuts: ["Vegetables", "Seeds", "Livestock", "Fertilizers", "Fruits", "Farmland"],
  toolsTitle: "Everything You Need to Manage Your Farm Better",
  toolsIntro: "Monitor crop health, plan what comes next, follow weather conditions and get practical support when you need it.",
  toolsBenefits: ["Everyday farm assistance", "Crop health monitoring", "Planning & timing guidance", "Weather & seasonal updates"],
  tools: [
    {name: "Ask Wuobi", description: "Everyday farming questions"},
    {name: "Crop Doctor", description: "Crop concerns"},
    {name: "Planting Advisor", description: "Planning what to plant"},
    {name: "Crop Calendar", description: "Planning seasonal tasks"}
  ],
  directoryTitle: "Farmers & Suppliers Directory",
  directoryTabs: ["Farmers", "Suppliers & Services"],
  directoryActions: ["View All Farmers", "View All Suppliers & Services"],
  toolsHeading: "Farming help, in one place.",
  marketplaceTitle: "Marketplace",
  marketplaceTabs: ["All", "Vegetables", "Fruits", "Livestock", "Farm inputs"],
  marketplaceAction: "View Marketplace",
  howTitle: "How Ghana Growers Works",
  steps: [
    {title: "Choose your path", text: "Farmer, buyer, supplier or service provider."},
    {title: "Explore", text: "Find produce, profiles and farming tools."},
    {title: "Check the details", text: "Read the available information and what still needs confirmation."},
    {title: "Take the next step", text: "Use an available application, enquiry or farming tool."}
  ],
  howAction: "See How It Works",
  learnTitle: "Learn",
  learnAction: "View All Learn",
  audienceTitle: "Your next step in agriculture",
  audiences: ["Farmer", "Buyer", "Supplier", "Partner"],
  unavailableAction: "Not available in this Preview",
  directoryUnavailable: "Directory search is unavailable in this Preview. No profiles or search results are being presented.",
  marketplaceUnavailable: "Listings are unavailable in this Preview. Prices, availability and seller details have not been supplied.",
  learnUnavailable: "Reviewed resources have not yet been selected for this homepage.",
  mediaUnavailable: "Provisional landscape placeholder · cultivated land / crops",
  productUnavailable: "Product-interface placeholder · not an operational screen",
  resourcePlaceholder: "Preview-only resource placeholder · no advice or reviewed article",
  cropPlaceholder: "Neutral image placeholder · not evidence of this listing",
  profilePlaceholder: "Neutral profile placeholder",
  servicePlaceholder: "Neutral service placeholder",
  footer: "Visual review only. No merge or Production release approved."
} as const;
