const {chromium}=require('C:/Users/lynne/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
const base=process.env.RC1_TEST_URL||'http://127.0.0.1:3109';
const deployed=base.startsWith('https://');const out=deployed?'.rc1-local/deployed-browser':'.rc1-local/browser';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const results=[];
try{const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push({url:new URL(page.url()).pathname,message:e.message}));
if(deployed){
 const anonymous=await browser.newContext();const denied=await anonymous.request.get(base+'/api/rc1-readiness',{maxRedirects:0});assert([302,401,403].includes(denied.status()));await anonymous.close();
 const access=JSON.parse(fs.readFileSync('.rc1-local/deployed-access.json','utf8'));await page.goto(access.shareUrl,{waitUntil:'networkidle'});assert((await context.cookies()).some(c=>c.name.startsWith('_vercel')));
 const readiness=await context.request.get(base+'/api/rc1-readiness');assert.equal(readiness.status(),200);const runtime=await readiness.json();assert.equal(runtime.stagingRef,'ecluxmyxqofkbzcyurlf');assert.equal(runtime.branch,'codex/p09-rc1');assert.equal(runtime.browserIsolationFlag,true);assert.equal(runtime.isolated,true);
 fs.writeFileSync(`${out}/runtime.json`,JSON.stringify(runtime,null,2));results.push({test:'Deployed identity, staging isolation, anonymous access denied',status:'PASS',commit:runtime.commit});
 // Deliberately malformed input proves these closed routes refuse before parsing.
 for(const path of ['buyer-registration','buyer-request-submissions','contact-enquiries','farmer-registration','farmmate/feedback','featured-enquiries','lead-requests','listing-submissions','supplier-registration','waitlist','whatsapp-leads']){
  const response=await context.request.post(base+'/api/'+path,{data:'RC1 disposable gate check: not JSON',headers:{'Content-Type':'application/json'}});assert.equal(response.status(),503,path);assert.equal((await response.json()).code,'PUBLIC_SUBMISSION_UNAVAILABLE');
 }
 results.push({test:'11 deployed unowned intake routes refuse malformed input before parsing',status:'PASS'});
 const privatePage=await context.request.get(base+'/dev-preview/amended-homepage');assert.equal(privatePage.status(),403);results.push({test:'App signed internal-preview access remains required after Vercel authentication',status:'PASS'});
}
// Local rendered validation deliberately blocks every external origin and public API write.
await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==base||(/\/api\//.test(u.pathname)&&route.request().method()!=='GET'))return route.abort();return route.continue()});
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});const response=await page.goto(base+'/',{waitUntil:'networkidle'});assert.equal(response.status(),200);await page.locator('h1').waitFor();await page.screenshot({path:`${out}/homepage-${width}.png`,fullPage:true});
const dims=await page.evaluate(()=>({footerHeight:document.querySelector('footer').getBoundingClientRect().height,width:innerWidth,scroll:document.documentElement.scrollWidth,body:document.body.scrollWidth,broken:[...document.images].filter(i=>i.offsetParent!==null&&!i.complete||i.offsetParent!==null&&i.naturalWidth===0).map(i=>i.getAttribute('src')),rows:[...document.querySelectorAll('footer nav a')].map(a=>a.getBoundingClientRect().height),social:[...document.querySelectorAll('footer button')].map(a=>[a.getBoundingClientRect().width,a.getBoundingClientRect().height])}));
assert(dims.scroll<=width+1,`overflow ${width}: ${dims.scroll}`);assert.equal(dims.broken.length,0,JSON.stringify(dims.broken));assert(dims.rows.every(x=>x===(width<601?32:30)));assert(dims.social.every(x=>x[0]===44&&x[1]===44));assert(Math.abs(dims.footerHeight-({320:550,390:530,768:356,1440:262}[width]))<=1,`Footer height ${width}: ${dims.footerHeight}`);
if(width<901){const menu=page.locator('button[aria-controls="rc1-mobile-menu"]');await menu.click();assert.equal(await menu.getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await menu.getAttribute('aria-expanded'),'false');assert(await menu.evaluate(e=>e===document.activeElement));}
const footer=page.locator('footer nav a').first();await footer.focus();await page.screenshot({path:`${out}/footer-focus-${width}.png`,fullPage:false});results.push({test:`Homepage ${width}: no overflow, images, footer geometry, menu/Escape`,status:'PASS',...dims});}
for(const path of ['/marketplace','/farmer-directory','/supplier-directory','/directory','/learn','/learn/weekly-crop-field-check','/contact','/join','/about/careers','/verification-process']){const r=await page.goto(base+path,{waitUntil:'networkidle'});assert.equal(r.status(),200,path);assert(!(await page.locator('body').innerText()).includes('Preview Farmer 01'));results.push({test:path,status:'PASS'});}
await page.setViewportSize({width:320,height:900});await page.goto(base+'/farmer-hub?tool=ask',{waitUntil:'networkidle'});await page.screenshot({path:`${out}/ask-disclosure-320.png`,fullPage:true});assert(await page.getByText('Ask Mama G uses AI to help answer farming questions.',{exact:false}).isVisible());
await page.goto(base+'/farmer-hub?tool=doctor',{waitUntil:'networkidle'});await page.screenshot({path:`${out}/crop-disclosure-320.png`,fullPage:true});assert(await page.getByText('Crop Doctor uses AI to analyse the crop photo you upload.',{exact:false}).isVisible());results.push({test:'320px text/photo disclosures before submission',status:'PASS'});
fs.writeFileSync(`${out}/results.json`,JSON.stringify({base,results,errors,externalRequestsBlocked:true,writesBlocked:true},null,2));assert.equal(errors.length,0,JSON.stringify(errors));console.log(JSON.stringify({passed:results.length,errors}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
