import {suppliersPath,providerUrl,type Provider} from "@/lib/suppliers-preview";
import styles from "@/styles/suppliers-preview.module.css";
export function ProviderProfile({provider:p,back,state}:{provider:Provider;back:string;state:string}){
 const unavailable=state==="unavailable"||state==="withdrawn",area=state==="under-review"?"Information under review":p.areaState;
 return <section data-provider-profile><a href={back}>Back to Suppliers &amp; Services</a>{unavailable?<div className={styles.state}><h1>Provider profile unavailable</h1><p>{state==="withdrawn"?"This synthetic profile represents a withdrawn record.":"Information is unavailable in this Preview scenario."}</p><a href={suppliersPath}>Browse providers</a></div>:<>
 <header className={styles.profileTop}><div><p className={styles.category}>{p.category}</p><h1>{p.name}</h1><dl className={styles.locations} data-provider-location><div><dt>Based in</dt><dd>{p.base}, {p.baseRegion}</dd></div><div><dt>Serves</dt><dd>{p.serves.join(" · ")||"Needs confirmation"}</dd></div></dl><p className={styles.small}>Service area: {area} · Synthetic provider</p></div><aside className={styles.enquiryIntro}><h2>Ask about relevant support</h2><p>Ghana Growers can help coordinate a next step. This Preview sends nothing.</p>{state==="enquiry-unavailable"?<p>Supplier enquiry unavailable</p>:<a className={styles.yellow} href={suppliersPath+"/enquiry?provider="+p.id+"&from="+encodeURIComponent(back)}>Ask about this supplier</a>}</aside></header>
 <section className={styles.section} data-provider-offerings><h2>What they offer</h2><ul className={styles.offerings}>{p.offerings.map(o=><li key={o}>{o}</li>)}</ul><p className={styles.small}>Synthetic participant-supplied examples. Availability and terms need confirmation.</p></section>
 <section className={styles.section}><h2>Service area</h2><p><strong>Based in:</strong> {p.base}, {p.baseRegion}</p><p><strong>Serves:</strong> {p.serves.join(" · ")||"Service area needs confirmation"}</p><p>{area}. Reported areas do not guarantee coverage for a particular request.</p></section>
 <section className={styles.section}><h2>About the provider</h2><p>{p.about}</p><p>Provider type: {p.type} · Preview fixture</p></section>
 <section className={styles.section} data-provider-evidence><h2>What we know about this profile</h2><dl className={styles.evidence}><div><dt>Offerings</dt><dd>Participant-reported · fictional example</dd></div><div><dt>Service area</dt><dd>{area}</dd></div><div><dt>Current availability</dt><dd>Needs confirmation</dd></div><div><dt>Supporting evidence</dt><dd>Unavailable</dd></div>{state==="checked"&&<div><dt>Example category-label check</dt><dd>Checked by Ghana Growers — synthetic demonstration only. Source: Preview category record; scope: label matches approved taxonomy; example reviewer: Preview reviewer; example date: 11 September 2026. No real provider or coverage was checked.</dd></div>}</dl><a href="/dev-preview/public/how-information-is-checked">How information is checked →</a></section>
 <a href={providerUrl(p.id,back)}>Return to profile overview</a></>}</section>;
}
