"use client";
import {useEffect,useRef,useState} from "react";
import {supplierCategories,supplierUrl,readSuppliers,matchingProviders,perPage,type Provider,type SupplierState} from "@/lib/suppliers-preview";
import {ProviderCard} from "./ProviderCard";
import styles from "@/styles/suppliers-preview.module.css";
export function SupplierBrowse({items,initial}:{items:Provider[];initial:SupplierState}){
 const [state,setState]=useState(initial),[query,setQuery]=useState(initial.q),[draft,setDraft]=useState(initial.region),[retry,setRetry]=useState(false);
 const categories=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{const mq=matchMedia("(min-width:640px)");const sync=()=>{if(categories.current)categories.current.open=mq.matches;};sync();mq.addEventListener("change",sync);return()=>mq.removeEventListener("change",sync);},[]);
 const results=useRef<HTMLHeadingElement>(null),dialog=useRef<HTMLDialogElement>(null),opener=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const restore=()=>{const s=readSuppliers(new URLSearchParams(location.search),items);setState(s);setQuery(s.q);requestAnimationFrame(()=>{const id=location.hash.slice(1);if(id)document.getElementById(id)?.focus();else results.current?.focus();});};const canonical=supplierUrl(initial)+location.hash;if(location.pathname+location.search+location.hash!==canonical)history.replaceState(null,"",canonical);if(location.hash)requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.focus());window.addEventListener("popstate",restore);return()=>window.removeEventListener("popstate",restore);},[initial,items]);
 function update(next:SupplierState,focus=true){const s=readSuppliers(new URL(supplierUrl(next),location.origin).searchParams,items);history.pushState(null,"",supplierUrl(s));setState(s);if(next.q!==state.q)setQuery(s.q);setRetry(false);if(focus)requestAnimationFrame(()=>results.current?.focus());}
 const matches=state.fixture?[]:matchingProviders(items,state),visible=matches.slice((state.page-1)*perPage,state.page*perPage),pages=Math.max(1,Math.ceil(matches.length/perPage)),regions=Array.from(new Set(items.flatMap(p=>p.serves))).sort();
 return <section data-supplier-browse><header className={styles.intro}><h1>Suppliers &amp; Services</h1><p>Find agricultural inputs, equipment and support providers.</p></header><form className={styles.searchForm} onSubmit={e=>{e.preventDefault();update({...state,q:query,page:1});}}><label htmlFor="supplier-search">Search providers, products, services or location</label><div className={styles.search}><input id="supplier-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} maxLength={120} placeholder="Search providers or services"/><button type="submit" className={styles.primary}>Search</button></div></form>
 <details ref={categories} className={styles.categories}><summary>Categories: {state.category||"All"}</summary><div role="group" aria-label="Supplier categories">{["All",...supplierCategories].map(c=><button key={c} type="button" aria-pressed={state.category===(c==="All"?"":c)} onClick={()=>update({...state,category:c==="All"?"":c,page:1},false)}>{c}</button>)}</div></details>
 <div className={styles.filters}><label className={styles.desktopFilter}>Serves region<select aria-label="Serves region" value={state.region} onChange={e=>update({...state,region:e.target.value,page:1})}><option value="">All service regions</option>{regions.map(r=><option key={r}>{r}</option>)}</select></label><button className={styles.mobileFilter} ref={opener} type="button" aria-haspopup="dialog" onClick={()=>{setDraft(state.region);dialog.current?.showModal();}}>Filters{state.region?" (1)":""}</button><p className={styles.small}>Service areas are participant-reported unless a specific check is stated.</p></div>
 <dialog ref={dialog} className={styles.dialog} aria-labelledby="supplier-filter-title" onClose={()=>opener.current?.focus()}><h2 id="supplier-filter-title">Filter by service area</h2><label htmlFor="serves-filter">Serves region</label><select id="serves-filter" value={draft} onChange={e=>setDraft(e.target.value)}><option value="">All service regions</option>{regions.map(r=><option key={r}>{r}</option>)}</select><div className={styles.actions}><button type="button" onClick={()=>setDraft("")}>Clear region</button><button type="button" onClick={()=>dialog.current?.close()}>Cancel</button><button type="button" className={styles.primary} onClick={()=>{update({...state,region:draft,page:1});dialog.current?.close();}}>Apply filters</button></div></dialog>
 {(state.q||state.category||state.region)&&<div className={styles.active} aria-label="Active search and filters">{(["q","category","region"] as const).filter(k=>state[k]).map(k=><button type="button" key={k} onClick={()=>update({...state,[k]:"",page:1})} aria-label={"Clear "+(k==="q"?"search":k)+": "+state[k]}>{state[k]} ×</button>)}<button type="button" onClick={()=>update({...state,category:"",region:"",page:1})}>Clear filters</button></div>}
 <h2 ref={results} tabIndex={-1} id="supplier-results" aria-live="polite">{state.fixture==="unavailable"?"Provider information unavailable":matches.length+" Preview providers"+(matches.length?" · Showing "+((state.page-1)*perPage+1)+"–"+Math.min(state.page*perPage,matches.length):"")}</h2>
 {state.fixture==="unavailable"?<div className={styles.state}><h3>Information unavailable</h3><p>The directory cannot be shown in this Preview scenario.</p><button type="button" onClick={()=>setRetry(true)}>Retry</button>{retry&&<p role="status">Still unavailable in this scenario. Search and filters are preserved.</p>}<a href={supplierUrl({...state,fixture:"",page:1})}>Return to Suppliers &amp; Services</a></div>:matches.length===0?<div className={styles.state}><h3>{state.fixture==="empty"?"No providers currently listed in this category":"No suppliers or services match these choices"}</h3><p>This state describes Preview fixtures, not real service availability.</p><a href={supplierUrl({q:"",category:"",region:"",page:1,fixture:""})}>Browse all categories</a><button type="button" onClick={()=>{setQuery("");update({q:"",category:"",region:"",page:1,fixture:""});}}>Clear search and filters</button></div>:<div className={styles.grid}>{visible.map(p=><ProviderCard key={p.id} provider={p} from={supplierUrl(state)}/>)}</div>}
 {pages>1&&<nav className={styles.actions} aria-label="Provider pages"><button type="button" disabled={state.page===1} onClick={()=>update({...state,page:state.page-1})}>Previous</button><span>Page {state.page} of {pages}</span><button type="button" disabled={state.page===pages} onClick={()=>update({...state,page:state.page+1})}>Next</button></nav>}
 </section>;
}
