"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {ghanaRegions} from "@/data/ghanaRegions";
import {supplierCategories} from "@/lib/suppliers-preview";
import styles from "@/styles/suppliers-preview.module.css";
type Field={id:string;label:string;required?:boolean;type?:"tel"|"textarea"|"multi";options?:readonly string[]};
type Group={title:string;fields:Field[]};
const enquiry:Group[]=[
 {title:"What do you need?",fields:[{id:"need",label:"Product / service needed",required:true},{id:"location",label:"Location",required:true},{id:"timing",label:"Timing"},{id:"details",label:"Additional details",type:"textarea"}]},
 {title:"Your details",fields:[{id:"name",label:"Name",required:true},{id:"phone",label:"Phone",required:true,type:"tel"},{id:"whatsapp",label:"WhatsApp",type:"tel"}]}
];
const entry:Group[]=[
 {title:"Provider + contact",fields:[{id:"provider",label:"Provider / business name",required:true},{id:"contact",label:"Primary contact name",required:true},{id:"phone",label:"Phone",required:true,type:"tel"},{id:"whatsapp",label:"WhatsApp",type:"tel"}]},
 {title:"What you offer",fields:[{id:"type",label:"Provider type",required:true,options:["Supplier","Service Provider","Both"]},{id:"categories",label:"Categories",required:true,type:"multi",options:supplierCategories},{id:"offerings",label:"Products and/or services offered",required:true,type:"textarea"},{id:"description",label:"Short description",type:"textarea"}]},
 {title:"Location + service area",fields:[{id:"region",label:"Base region",required:true,options:ghanaRegions},{id:"district",label:"District / community"},{id:"serves",label:"Regions served",type:"multi",options:ghanaRegions}]},
 {title:"Supporting information",fields:[{id:"notes",label:"Additional service/product details or notes",type:"textarea"}]}
];
export function SupplierFlow({mode,providerName,back}:{mode:"enquiry"|"entry";providerName?:string;back:string}){
 const groups=mode==="enquiry"?enquiry:entry,title=mode==="enquiry"?"Ask about this supplier":"List a Product or Service";
 const [values,setValues]=useState<Record<string,string>>({}),[multi,setMulti]=useState<Record<string,string[]>>({}),[step,setStep]=useState(0),[complete,setComplete]=useState(false),[ready,setReady]=useState(false),[files,setFiles]=useState<File[]>([]),[errors,setErrors]=useState<Record<string,string>>({});
 const heading=useRef<HTMLHeadingElement>(null),moved=useRef(false),pendingFocus=useRef<string>();
 useEffect(()=>setReady(true),[]);
 useEffect(()=>{if(moved.current){const error=pendingFocus.current;pendingFocus.current=undefined;if(error)document.getElementById(error)?.focus();else heading.current?.focus();}},[step,complete,errors]);
 function go(n:number){moved.current=true;setErrors({});setStep(n);setComplete(false);}
 function validate(n:number){const e:Record<string,string>={};for(const f of groups[n].fields){const v=(values[f.id]||"").trim(),m=multi[f.id]||[];if(f.required&&!(f.type==="multi"?m.length:v))e[f.id]="Enter "+f.label.toLowerCase()+".";if(v.length>(f.type==="textarea"?1500:160))e[f.id]="Shorten "+f.label.toLowerCase()+".";if(f.type==="tel"&&v&&(!/^[+\d\s().-]{7,30}$/.test(v)||v.replace(/\D/g,"").length<7))e[f.id]="Enter a valid "+f.label.toLowerCase()+".";if(f.options&&(f.type==="multi"?m.some(x=>!f.options!.includes(x)):v&&!f.options.includes(v)))e[f.id]="Choose an available option.";}if(mode==="entry"&&n===3&&(files.length>5||files.some(f=>!["image/jpeg","image/png","image/webp"].includes(f.type)||f.size>5*1024*1024)))e.photos="Use up to five JPG, PNG or WEBP test images, each no larger than 5MB.";return e;}
 function showErrors(e:Record<string,string>,n:number){moved.current=true;pendingFocus.current=Object.keys(e)[0];setStep(n);setErrors(e);}
 function submit(e:FormEvent){e.preventDefault();const invalid=validate(step);if(Object.keys(invalid).length)showErrors(invalid,step);else go(step+1);}
 function finish(){for(let i=0;i<groups.length;i++){const invalid=validate(i);if(Object.keys(invalid).length){showErrors(invalid,i);return;}}moved.current=true;setComplete(true);}
 function value(f:Field){return f.type==="multi"?(multi[f.id]||[]).join(" · "):values[f.id];}
 function renderField(f:Field){const help=errors[f.id]?f.id+"-error":undefined;if(f.type==="multi")return <fieldset key={f.id} className={styles.multi}><legend>{f.label} ({f.required?"required":"optional"})</legend><div id={f.id} tabIndex={-1} role="group" aria-label={f.label} aria-describedby={help} className={styles.checkGrid}>{f.options!.map(o=><label key={o}><input type="checkbox" checked={(multi[f.id]||[]).includes(o)} onChange={e=>setMulti({...multi,[f.id]:e.target.checked?[...(multi[f.id]||[]),o]:(multi[f.id]||[]).filter(x=>x!==o)})}/><span>{o}</span></label>)}</div>{errors[f.id]&&<p id={help} className={styles.error}>{errors[f.id]}</p>}</fieldset>;
 const props={id:f.id,value:values[f.id]||"",required:f.required,"aria-invalid":Boolean(errors[f.id]),"aria-describedby":help,onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>setValues({...values,[f.id]:e.target.value})};
 return <div key={f.id} className={styles.field}><label htmlFor={f.id}>{f.label} ({f.required?"required":"optional"})</label>{f.options?<select {...props}><option value="">Choose an option</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==="textarea"?<textarea {...props} maxLength={1500}/>:<input {...props} type={f.type||"text"} maxLength={160}/>} {errors[f.id]&&<p id={help} className={styles.error}>{errors[f.id]}</p>}</div>;}
 const reviewGroups=mode==="enquiry"?[{title:"Enquiry",fields:enquiry[0].fields,step:0},{title:"Contact",fields:enquiry[1].fields,step:1}]:[{title:"Provider",fields:entry[0].fields.slice(0,1),step:0},{title:"Contact",fields:entry[0].fields.slice(1),step:0},{title:"Offerings",fields:entry[1].fields,step:1},{title:"Location",fields:entry[2].fields.slice(0,2),step:2},{title:"Service area",fields:entry[2].fields.slice(2),step:2},{title:"Supporting information",fields:entry[3].fields,step:3}];
 return <section data-supplier-flow={mode} className={styles.flow}><a href={back}>Back to {mode==="enquiry"?"provider profile":"listing options"}</a><header className={styles.intro}><h1>{title}</h1><p>{mode==="entry"?"Provider participation / profile entry":"A mediated Ghana Growers enquiry"}</p></header><aside className={styles.notice}><strong>Local Preview only</strong><p>Use fictional details{mode==="entry"?" and test files":""}. Nothing is sent, saved, uploaded or published. Reloading clears this demonstration.</p></aside>{providerName&&<p data-enquiry-provider><strong>Provider:</strong> {providerName} · synthetic context</p>}
 <ol className={styles.progress} aria-label={title+" progress"}>{[...groups.map(g=>g.title),"Review"].map((g,i)=><li key={g} aria-current={!complete&&i===step?"step":undefined}><span>{i+1}</span>{g}</li>)}</ol>
 {complete?<section role="status" className={styles.state}><h2 ref={heading} tabIndex={-1}>Preview {mode==="entry"?"supplier entry":"enquiry"} complete</h2><p><strong>Nothing was sent.</strong> Nothing was submitted, saved, uploaded, approved, verified or published.</p><p>{mode==="enquiry"?"No supplier was contacted. No service was booked. No order, transaction, enquiry ID, receipt, notification, database or account record was created.":"No supplier account, live profile, Marketplace listing, notification or publication ID was created."}</p><p>This confirms local validation only. Live {mode==="entry"?"provider intake, moderation and publication":"enquiry receiving and follow-up"} remains a release dependency.</p><button type="button" onClick={()=>go(groups.length)}>Review Preview details</button><a href={back}>Return to source</a></section>:<><p className={styles.small}>Step {step+1} of {groups.length+1}</p><h2 tabIndex={-1} ref={heading}>{step===groups.length?"Review":groups[step].title}</h2>
 {step===groups.length?<section data-supplier-review>{reviewGroups.map(g=><section key={g.title} className={styles.reviewGroup}><h3>{g.title}</h3><dl>{g.fields.map(f=><div key={f.id}><dt>{f.label}</dt><dd>{value(f)||"Not provided"}</dd></div>)}</dl>{g.title==="Supporting information"&&<p>{files.length} local test images selected. File contents are not read or uploaded.</p>}<button type="button" aria-label={"Edit "+g.title} onClick={()=>go(g.step)}>Edit</button></section>)}<div className={styles.actions}><button type="button" onClick={()=>go(0)}>{mode==="enquiry"?"Edit enquiry":"Edit entry"}</button><button type="button" className={styles.primary} onClick={finish}>Complete Preview {mode==="entry"?"supplier entry":"enquiry"}</button></div></section>:<form noValidate onSubmit={submit}><fieldset disabled={!ready} className={styles.formFields}>
 {Object.keys(errors).length>0&&<div role="alert" className={styles.errors}><h3>Review these fields</h3>{Object.entries(errors).map(([id,message])=><a key={id} href={"#"+id} onClick={e=>{e.preventDefault();document.getElementById(id)?.focus();}}>{message}</a>)}</div>}
 {mode==="entry"&&step===2&&<p>Base region is where you are based. Regions served describe where you report you can serve; this is not independently checked. Leave service regions blank if they need confirmation.</p>}
 {groups[step].fields.map(renderField)}
 {mode==="entry"&&step===3&&<div className={styles.field}><label htmlFor="photos">Context images (optional)</label><input id="photos" type="file" multiple accept="image/jpeg,image/png,image/webp" aria-describedby={errors.photos?"photos-help photos-error":"photos-help"} aria-invalid={Boolean(errors.photos)} onChange={e=>setFiles(Array.from(e.target.files||[]))}/><p className={styles.small} id="photos-help">Up to five JPG, PNG or WEBP test images, 5MB each. Metadata validation only; nothing is uploaded. Do not provide identity documents or business certificates. Images do not prove stock, ownership, service quality or coverage.</p>{files.length>0&&<p>{files.length} test images selected locally</p>}{errors.photos&&<p id="photos-error" className={styles.error}>{errors.photos}</p>}</div>}
 <div className={styles.actions}>{step>0&&<button type="button" onClick={()=>go(step-1)}>Back</button>}<button type="submit" className={styles.primary}>{step===groups.length-1?"Review":"Continue"}</button></div></fieldset></form>}</>}
 </section>;
}
