"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {ghanaRegions} from "@/data/ghanaRegions";
import styles from "@/styles/marketplace-preview.module.css";
type Field={id:string;label:string;required?:boolean;type?:string;options?:readonly string[];max?:number};
type Group={title:string;fields:Field[]};
const delivery=["Buyer pickup","Deliver to buyer","Collection point","Flexible / discuss with Ghana Growers"];
const requestGroups:Group[]=[
 {title:"What you need",fields:[{id:"product",label:"Product",required:true},{id:"quantity",label:"Quantity",required:true},{id:"unit",label:"Quantity unit",required:true},{id:"timing",label:"Required by / timing",required:true},{id:"notes",label:"Additional sourcing details",type:"textarea",max:1500}]},
 {title:"Location & delivery",fields:[{id:"region",label:"Region",required:true,options:ghanaRegions},{id:"district",label:"District / delivery location",required:true},{id:"delivery",label:"Preferred delivery / collection",options:delivery}]},
 {title:"Your details",fields:[{id:"name",label:"Name",required:true},{id:"company",label:"Company"},{id:"phone",label:"Phone",required:true,type:"tel"},{id:"whatsapp",label:"WhatsApp",type:"tel"},{id:"email",label:"Email",type:"email"}]}
];
const listingGroups:Group[]=[
 {title:"Seller & location",fields:[{id:"name",label:"Name",required:true},{id:"business",label:"Farm / business name"},{id:"phone",label:"Phone",required:true,type:"tel"},{id:"whatsapp",label:"WhatsApp",type:"tel"},{id:"region",label:"Region",required:true,options:ghanaRegions},{id:"district",label:"District / town",required:true}]},
 {title:"Product details",fields:[{id:"product",label:"Product",required:true},{id:"category",label:"Category",required:true,options:["Fresh Produce","Livestock"]},{id:"variety",label:"Variety / product details"},{id:"description",label:"Short description",type:"textarea",max:1500}]},
 {title:"Availability & quantity",fields:[{id:"availability",label:"Reported availability",required:true,options:["Needs confirmation","Unavailable","Available now — synthetic test value","Seasonal — synthetic test value"]},{id:"quantity",label:"Quantity (or needs confirmation)"},{id:"unit",label:"Quantity unit",required:true},{id:"frequency",label:"Supply frequency",required:true,options:["One-off","Seasonal","Regular","Needs confirmation"]},{id:"availableFrom",label:"Harvest / available-from timing"},{id:"price",label:"Price per unit (or needs confirmation)"},{id:"pickup",label:"Collection location",required:true},{id:"delivery",label:"Collection / delivery preference",options:delivery}]},
 {title:"Photos & supporting information",fields:[{id:"notes",label:"Additional details",type:"textarea",max:1500}]}
];
// P05-5 125:16: provisional coordination wording, demonstrated locally only.
const consentCopy="I agree that Ghana Growers may use the details I provide to review and coordinate this request and contact me about it. Relevant request details may be shared with suitable farmers or suppliers where necessary to explore a response. Submitting a request does not guarantee availability, price, delivery or fulfilment.";
export function MarketplacePreviewForm({mode,context,product,back}:{mode:"request"|"listing";context?:string;product?:string;back:string}) {
 const groups=mode==="request"?requestGroups:listingGroups,total=groups.length+1;
 const [step,setStep]=useState(0),[complete,setComplete]=useState(false),[values,setValues]=useState<Record<string,string>>({product:product||""}),[files,setFiles]=useState<File[]>([]),[agreement,setAgreement]=useState(false),[same,setSame]=useState(false),[errors,setErrors]=useState<Record<string,string>>({}),[ready,setReady]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null),moved=useRef(false);
 useEffect(()=>setReady(true),[]);
 useEffect(()=>{if(moved.current)heading.current?.focus();},[step,complete]);
 function go(next:number){moved.current=true;setErrors({});setComplete(false);setStep(next);}
 function validate(index:number){const next:Record<string,string>={};for(const f of groups[index].fields){const v=(values[f.id]||"").trim();if(f.required&&!v)next[f.id]=`Enter ${f.label.toLowerCase()}.`;if(v.length>(f.max||160))next[f.id]=`${f.label} is too long.`;if(f.type==="tel"&&v&&!/^[+\d\s().-]{7,30}$/.test(v))next[f.id]=`Enter a valid ${f.label.toLowerCase()}.`;if(f.type==="email"&&v&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))next[f.id]="Enter a valid email.";if(f.options&&v&&!f.options.includes(v))next[f.id]="Choose an available option.";}
 if(index===groups.length-1&&!agreement)next.agreement=mode==="request"?"Confirm the Preview coordination consent.":"Confirm the Preview information statement.";
 if(mode==="listing"&&index===3&&(files.length>5||files.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024)))next.photos="Use up to five JPG, PNG or WEBP test images, each no larger than 5MB.";
 return next;}
 function submit(e:FormEvent){e.preventDefault();const next=validate(step);setErrors(next);if(Object.keys(next).length){requestAnimationFrame(()=>document.getElementById(Object.keys(next)[0])?.focus());return;}go(step+1);}
 function finish(){for(let i=0;i<groups.length;i++){const next=validate(i);if(Object.keys(next).length){go(i);setErrors(next);requestAnimationFrame(()=>document.getElementById(Object.keys(next)[0])?.focus());return;}}moved.current=true;setComplete(true);}
 const title=mode==="request"?"Request Produce":"List Produce",review=step===groups.length;
 function field(f:Field){const props={id:f.id,required:f.required,"aria-invalid":Boolean(errors[f.id]),"aria-describedby":errors[f.id]?`${f.id}-error`:undefined,value:values[f.id]||"",onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>setValues({...values,[f.id]:e.target.value,...(f.id==="phone"&&same?{whatsapp:e.target.value}:{})})};return <div key={f.id} className={`${styles.field} ${f.type==="textarea"?styles.wide:""}`}><label htmlFor={f.id}>{f.label} <span className={styles.small}>({f.required?"required":"optional"})</span></label>{f.options?<select {...props}><option value="">Choose an option</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==="textarea"?<textarea {...props} maxLength={f.max||160}/>:<input {...props} type={f.type||"text"} maxLength={f.max||160} disabled={f.id==="whatsapp"&&same}/>} {errors[f.id]&&<span id={`${f.id}-error`} className={styles.error}>{errors[f.id]}</span>}</div>;}
 return <section data-marketplace-form={mode} className={styles.flow}><a className={styles.back} href={back}>Back to {mode==="request"?"source":"listing options"}</a><header className={styles.gatewayHeading}><h1>{title}</h1><p>{mode==="request"?"Tell us what you need, then review your request.":"Describe your produce, then review the details."}</p></header>
 <aside className={styles.flowNotice}><strong>Local Preview only</strong><p>Use fictional details and test files. Nothing is sent, saved, uploaded or published. Reloading clears this demonstration.</p>{context&&<p data-source-context><strong>Source:</strong> {context} · synthetic context</p>}</aside>
 <ol className={styles.progress} aria-label={`${title} progress`}>{[...groups.map(g=>g.title),"Review"].map((label,i)=><li key={label} aria-current={!complete&&step===i?"step":undefined}><span aria-hidden="true">{i+1}</span>{label}</li>)}</ol>
 {complete?<section className={styles.completion} role="status"><h2 ref={heading} tabIndex={-1}>Preview {mode==="request"?"request":"listing"} complete</h2><p><strong>Nothing was sent.</strong> Nothing was saved, submitted, uploaded or published. This confirms local validation only.</p><p>No receipt, reference number, order, sourcing request, seller account, notification or published record was created.</p><p>Live {mode==="request"?"sourcing submission and follow-up":"listing intake and publication"} remains a release dependency.</p><div className={styles.actions}><button onClick={()=>go(groups.length)}>Review Preview details</button><a href={back}>Return to source</a></div></section>:<>
 <p className={styles.small}>Step {step+1} of {total}</p><h2 ref={heading} tabIndex={-1}>{review?"Review":groups[step].title}</h2>
 {review?<section data-form-review><p>Check these fictional details. Completing this Preview only validates them locally.</p>{groups.map((g,i)=><section key={g.title} className={styles.reviewGroup}><h3>{mode==="listing"?["Seller","Product","Availability","Additional details"][i]:g.title}</h3><dl className={styles.reviewList}>{g.fields.filter(f=>values[f.id]?.trim()).map(f=><div key={f.id}><dt>{f.label}</dt><dd>{values[f.id]}</dd></div>)}</dl><button type="button" onClick={()=>go(i)} aria-label={`Edit ${g.title}`}>Edit</button></section>)}{mode==="listing"&&<section className={styles.reviewGroup}><h3>Photos / files</h3><p>{files.length} test images selected. File contents are not read or uploaded.</p></section>}<p className={styles.small}>{mode==="request"?"Coordination consent":"Information statement"}: selected for this local demonstration only; not recorded.</p><div className={styles.actions}><button onClick={()=>go(0)}>{mode==="request"?"Edit request":"Edit listing"}</button><button className={styles.primary} onClick={finish}>Complete Preview {mode==="request"?"request":"listing"}</button></div></section>:<form className={styles.form} noValidate onSubmit={submit}><fieldset disabled={!ready}>
 {Object.keys(errors).length>0&&<div className={styles.errors} role="alert"><h3>Review these fields</h3><ul>{Object.entries(errors).map(([id,message])=><li key={id}><a href={`#${id}`} onClick={e=>{e.preventDefault();document.getElementById(id)?.focus();}}>{message}</a></li>)}</ul></div>}
 <div className={styles.fields}>{groups[step].fields.map(field)}</div>
 {groups[step].fields.some(f=>f.id==="whatsapp")&&<label className={styles.check}><input type="checkbox" checked={same} onChange={e=>{setSame(e.target.checked);if(e.target.checked)setValues({...values,whatsapp:values.phone||""});}}/><span>WhatsApp is the same as phone</span></label>}
 {mode==="request"&&step===1&&<p className={styles.small}>A delivery preference does not establish delivery availability or responsibility.</p>}
 {mode==="listing"&&step===2&&<p className={styles.small}>Participant-reported demonstration values; no independent confirmation.</p>}
 {mode==="listing"&&step===3&&<div className={styles.field}><label htmlFor="photos">Test product images (optional)</label><input id="photos" type="file" multiple accept="image/jpeg,image/png,image/webp" aria-invalid={Boolean(errors.photos)} aria-describedby={errors.photos?"photos-help photos-error":"photos-help"} onChange={e=>setFiles(Array.from(e.target.files||[]))}/><p id="photos-help" className={styles.small}>Up to five images, 5MB each. File contents are not read or uploaded. Images do not prove stock, quantity, quality, certification or ownership.</p>{files.length>0&&<p>{files.length} test files selected locally</p>}{errors.photos&&<span id="photos-error" className={styles.error}>{errors.photos}</span>}</div>}
 {step===groups.length-1&&<><p className={styles.small}>{mode==="request"?"Preview consent demonstration — provisional Phase 05 wording; legal review remains required. No consent is recorded or information shared.":"Local information statement only; not sent or recorded."}</p><label className={styles.check}><input id="agreement" type="checkbox" checked={agreement} aria-invalid={Boolean(errors.agreement)} aria-describedby={errors.agreement?"agreement-error":undefined} onChange={e=>setAgreement(e.target.checked)}/><span>{mode==="request"?consentCopy:"Preview statement: I confirm the information and photos are accurate to the best of my knowledge."}</span></label>{errors.agreement&&<p id="agreement-error" className={styles.error}>{errors.agreement}</p>}</>}
 <div className={styles.actions}>{step>0&&<button type="button" onClick={()=>go(step-1)}>Back</button>}<button type="submit" className={styles.primary}>{step===groups.length-1?"Review":"Continue"}</button></div></fieldset></form>}</>}
 </section>;
}
