"use client";
import {useState} from "react";
import {ProduceMedia} from "@/components/homepage/PreviewMedia";
import {listingUrl,sourcingUrl,type MarketplaceFixture} from "@/lib/marketplace-preview";
import styles from "@/styles/marketplace-preview.module.css";
export function MarketplacePreviewDetail({item,back,scenario,related=[]}:{item:MarketplaceFixture;back:string;scenario:string;related?:MarketplaceFixture[]}) {
 const [retry,setRetry]=useState(false),self=listingUrl(item.id,back);
 if(scenario==="unavailable"||scenario==="withdrawn")return <section data-marketplace-detail><a className={styles.back} href={back}>Back to Marketplace</a><h1>Listing unavailable</h1><div className={styles.state}><p>{scenario==="unavailable"?"This listing could not be loaded in the Preview scenario.":"This listing is not available for viewing."}</p>{scenario==="unavailable"&&<button type="button" onClick={()=>setRetry(true)}>Retry</button>}{retry&&<p role="status">The deliberate unavailable fixture remains unavailable. Your Marketplace choices are preserved.</p>}<a href="/dev-preview/request-produce">Request Produce</a></div></section>;
 const profile=item.farmerId?`/dev-preview/farmers/${item.farmerId}?listing=${encodeURIComponent(item.id)}&marketFrom=${encodeURIComponent(back)}`:undefined;
 return <article data-marketplace-detail><a className={styles.back} href={back}>Back to Marketplace</a><div className={styles.productTop}><div className={styles.productMedia}><ProduceMedia image={item.image} category={item.subcategory}/></div><header><p className={styles.small}>{item.category} · {item.subcategory}</p><h1>{item.product}</h1><p>{item.region}</p><div className={styles.sellerInline}><span className={styles.neutralIdentity} aria-hidden="true">GG</span><div><strong>{item.farmerName||item.seller}</strong><p className={styles.small}>Synthetic farmer / seller</p>{profile&&<a href={profile}>View Farmer Profile</a>}</div></div><p><strong>Needs confirmation:</strong> current availability</p><p>Explore this {item.product.toLowerCase()} listing and explain the quantity and timing you need.</p><dl className={styles.keyFacts}><div><dt>Quantity / stock</dt><dd>Unavailable</dd></div><div><dt>Price</dt><dd>Unavailable</dd></div><div><dt>Collection / delivery</dt><dd>Needs confirmation</dd></div></dl><div className={styles.productAction}><h2>Interested in this produce?</h2><p>Tell us what you need. Ghana Growers can help coordinate the next step.</p><a className={`${styles.primary} ${styles.yellow}`} href={sourcingUrl("listing",item.id,back)}>Request Produce</a><p className={styles.small}>Local Preview only. Nothing is sent; no order or reservation.</p></div></header></div>
 <section className={styles.detailSection}><h2>About this produce</h2><p>{item.product} · {item.subcategory} · {item.region}</p><p className={styles.small}>Synthetic listing for interface review. No real stock, price, quality or harvest is established.</p></section>
 <section className={styles.detailSection} data-seller-relationship><h2>Farmer / seller</h2><p>{item.seller} · {item.region}</p>{profile?<><p>This fixture is associated with {item.farmerName} for navigation review only. It establishes no real seller/farmer relationship.</p><a href={profile}>View Farmer Profile</a></>:<p>No farmer profile relationship is established for this fixture.</p>}</section>
 <section className={styles.detailSection} data-listing-evidence><h2>What we know about this listing</h2>{scenario==="checked"?<><p><strong>Checked by Ghana Growers — fixture demonstration only</strong></p><p>Simulated scope: the product label. Source: a synthetic Preview record. Example date: <time dateTime="2026-09-08">8 September 2026</time>.</p><p>No real check occurred. This is not evidence of seller identity, stock, quality or availability.</p></>:scenario==="under-review"?<><p><strong>Information under review — fixture demonstration</strong></p><p>Optional listing detail is withheld. No private review reason is displayed.</p></>:<><p><strong>Farmer-reported — fixture demonstration</strong></p><p>Product information demonstrates participant-supplied information, not a real farmer report.</p></>}<p><strong>Needs confirmation:</strong> availability and commercial details. Quality, certification and payment terms are unavailable.</p><a href="/dev-preview/public/how-information-is-checked">How information is checked</a><p className={styles.small}>Ghana Growers coordinates enquiries; it is not the seller. No payment, match, quality or delivery guarantee.</p></section>
 <section className={styles.detailSection} data-related-produce><h2>Related Produce</h2><p className={styles.small}>Other synthetic listings in {item.category}. Category grouping only.</p><div className={styles.grid}>{related.map(other=><article key={other.id} className={styles.card}><ProduceMedia image={other.image} category={other.subcategory}/><h3>{other.product}</h3><p>{other.region}</p><a href={listingUrl(other.id,back)} aria-label={`View details: ${other.product}, ${other.title}`}>View details</a></article>)}</div>{!related.length&&<p>No other Preview listings in this category.</p>}<a href={back}>Back to Marketplace</a></section>
 <nav className={styles.actions} aria-label="Listing support"><a href="/dev-preview/public/contact">Report incorrect listing information</a><a href={self}>Reset listing demonstration</a></nav><p className={styles.small}>Contact remains unavailable in Preview. No report is sent.</p></article>;
}
