"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {ghanaRegions} from "@/data/ghanaRegions";
import styles from "@/styles/marketplace-preview.module.css";
type Field={id:string;label:string;required?:boolean;type?:string;options?:readonly string[];max?:number};
type Group={title:string;fields:Field[]};
const requestGroups:Group[]=[{title:"Your sourcing need",fields:[{id:"product",label:"Product needed",required:true},{id:"quantity",label:"Quantity needed",required:true},{id:"region",label:"Region",required:true,options:ghanaRegions},{id:"district",label:"District / delivery location",required:true},{id:"timing",label:"Required by",type:"date"},{id:"delivery",label:"Preferred delivery",options:["Buyer pickup","Deliver to buyer","Collection point","Flexible / discuss with Ghana Growers"]},{id:"notes",label:"Additional sourcing details",type:"textarea",max:1500}]},{title:"Contact information",fields:[{id:"name",label:"Your name",required:true},{id:"company",label:"Company name"},{id:"phone",label:"Phone number",type:"tel",required:true},{id:"whatsapp",label:"WhatsApp number",type:"tel"}]}];
const listingGroups:Group[]=[{title:"Seller and contact",fields:[{id:"sellerType",label:"Seller type",required:true,options:["Farmer","Supplier","Other (review required)"]},{id:"business",label:"Farm or business name",required:true},{id:"name",label:"Contact person",required:true},{id:"phone",label:"Phone number",type:"tel",required:true},{id:"whatsapp",label:"WhatsApp number",type:"tel"},{id:"region",label:"Region",required:true,options:ghanaRegions},{id:"district",label:"District or town",required:true},{id:"member",label:"Already part of Ghana Growers?",required:true,options:["Yes","No","Not sure"]}]},{title:"Product details",fields:[{id:"product",label:"Product / listing title",required:true},{id:"category",label:"Category",required:true,options:["Fresh Produce","Farm Inputs","Livestock","Tools & Equipment"]},{id:"subcategory",label:"Subcategory"},{id:"variety",label:"Variety / product details"},{id:"grade",label:"Grade / condition description"},{id:"description",label:"Product description",type:"textarea",max:1500}]},{title:"Price and quantity",fields:[{id:"unit",label:"Selling unit",required:true},{id:"price",label:"Price per unit (or needs confirmation)"},{id:"unitSize",label:"Amount inside one unit"},{id:"quantity",label:"Quantity (or needs confirmation)"},{id:"minimum",label:"Minimum order, if applicable"}]},{title:"Availability and collection",fields:[{id:"availability",label:"Reported availability",required:true,options:["Available now — synthetic test value","Seasonal — synthetic test value","Needs confirmation","Unavailable"]},{id:"frequency",label:"Supply frequency",required:true,options:["One-off","Seasonal","Regular","Needs confirmation"]},{id:"availableFrom",label:"Available-from / harvest date",type:"date"},{id:"pickup",label:"Pickup location",required:true},{id:"delivery",label:"Delivery available",options:["Yes — synthetic test value","No","To be confirmed"]}]}];
export function MarketplacePreviewForm({mode,context,product,back}:{mode:"request"|"listing";context?:string;product?:string;back:string}) {
 const groups=mode==="request"?requestGroups:listingGroups,fields=groups.flatMap(g=>g.fields),[values,setValues]=useState<Record<string,string>>({product:product||""}),[files,setFiles]=useState<File[]>([]),[agreement,setAgreement]=useState(false),[same,setSame]=useState(false),[errors,setErrors]=useState<Record<string,string>>({}),[step,setStep]=useState<"edit"|"review"|"complete">("edit"),[ready,setReady]=useState(false),summary=useRef<HTMLDivElement>(null),heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>setReady(true),[]);
 useEffect(()=>{if(step!=="edit")heading.current?.focus();},[step]);
 function submit(e:FormEvent){e.preventDefault();const next:Record<string,string>={};for(const f of fields){const v=(values[f.id]||"").trim();if(f.required&&!v)next[f.id]=`Enter ${f.label.toLowerCase()}.`;if(v.length>(f.max||160))next[f.id]=`${f.label} is too long.`;if(f.type==="tel"&&v&&!/^[+\d\s().-]{7,30}$/.test(v))next[f.id]=`Enter a valid ${f.label.toLowerCase()}.`;}if(mode==="listing"&&!agreement)next.agreement="Confirm the Preview information statement.";if(files.length>5||files.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024))next.photos="Use up to five JPG, PNG or WEBP test images, each no larger than 5MB.";setErrors(next);if(Object.keys(next).length){requestAnimationFrame(()=>summary.current?.focus());return;}setStep("review");}
 const title=mode==="request"?"Request Produce":"List a Product";
 return <section data-marketplace-form={mode}><a className={styles.back} href={back}>Back to {mode==="request"?"source":"listing options"}</a><header className={styles.hero}><h1>{title}</h1><p>{mode==="request"?"Tell us what you are looking for.":"Describe a product for review."}</p></header><div className={styles.state}><strong>Local Preview only</strong><p>Use fictional details and test files only. Nothing is sent, uploaded, saved or published. Reloading clears this form.</p>{context&&<p data-source-context><strong>Source:</strong> {context} · synthetic context only</p>}{mode==="request"&&<p>A request is not an order or a guarantee of supply, quality, price, delivery or a match. No payment is taken.</p>}</div>
 {step==="complete"?<div className={styles.state} role="status"><h2 ref={heading} tabIndex={-1}>Preview {mode==="request"?"request":"listing"} complete</h2><p><strong>Nothing was sent.</strong> This confirms local validation only. No receipt, reference, order or published listing was created.</p><p>{mode==="request"?"A live request needs an approved receiving and follow-up workflow.":"A live listing needs approved intake, review, publication permission and evidence."}</p><div className={styles.actions}><button type="button" onClick={()=>setStep("review")}>Review Preview details</button><a href={back}>Return to source</a></div></div>:step==="review"?<section className={styles.panel} data-form-review><h2 ref={heading} tabIndex={-1}>Review {mode==="request"?"sourcing request":"listing details"}</h2><p>Check these fictional details. Continuing only completes this local demonstration.</p><dl className={styles.reviewList}>{fields.filter(f=>values[f.id]?.trim()).map(f=><div key={f.id}><dt>{f.label}</dt><dd>{values[f.id]}</dd></div>)}{files.length>0&&<><dt>Test images</dt><dd>{files.length} selected · metadata checked only</dd></>}</dl><div className={styles.actions}><button type="button" onClick={()=>{setStep("edit");requestAnimationFrame(()=>document.getElementById(fields[0].id)?.focus());}}>Edit details</button><button type="button" className={styles.primary} onClick={()=>setStep("complete")}>Complete Preview only</button></div></section>:<form className={styles.form} onSubmit={submit} noValidate><fieldset disabled={!ready}>
 {Object.keys(errors).length>0&&<div className={styles.errors} ref={summary} tabIndex={-1} role="alert"><h2>Review these fields</h2><ul>{Object.entries(errors).map(([id,message])=><li key={id}><a href={`#${id}`} onClick={e=>{e.preventDefault();document.getElementById(id)?.focus();}}>{message}</a></li>)}</ul></div>}
 {groups.map(g=><fieldset key={g.title}><legend>{g.title}</legend><div className={styles.fields}>{g.fields.map(f=><label key={f.id} className={`${styles.field} ${f.type==="textarea"?styles.wide:""}`} htmlFor={f.id}>{f.label} ({f.required?"required":"optional"}){f.options?<select id={f.id} required={f.required} value={values[f.id]||""} aria-invalid={Boolean(errors[f.id])} aria-describedby={errors[f.id]?`${f.id}-error`:undefined} onChange={e=>setValues({...values,[f.id]:e.target.value})}><option value="">Choose an option</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==="textarea"?<textarea id={f.id} maxLength={f.max||160} value={values[f.id]||""} aria-invalid={Boolean(errors[f.id])} aria-describedby={errors[f.id]?`${f.id}-error`:undefined} onChange={e=>setValues({...values,[f.id]:e.target.value})}/>:<input id={f.id} type={f.type||"text"} required={f.required} maxLength={f.max||160} value={f.id==="whatsapp"&&same?values.phone||"":values[f.id]||""} disabled={f.id==="whatsapp"&&same} aria-invalid={Boolean(errors[f.id])} aria-describedby={errors[f.id]?`${f.id}-error`:undefined} onChange={e=>setValues({...values,[f.id]:e.target.value,...(f.id==="phone"&&same?{whatsapp:e.target.value}:{})})}/>} {errors[f.id]&&<span id={`${f.id}-error`} className={styles.error}>{errors[f.id]}</span>}</label>)}</div></fieldset>)}
 <label className={styles.check}><input type="checkbox" checked={same} onChange={e=>{setSame(e.target.checked);if(e.target.checked)setValues({...values,whatsapp:values.phone||""});}}/><span>WhatsApp is the same as phone</span></label>
 {mode==="listing"&&<><label className={styles.field} htmlFor="photos">Test product images (optional)<input id="photos" type="file" multiple accept="image/jpeg,image/png,image/webp" aria-invalid={Boolean(errors.photos)} aria-describedby={errors.photos?"photos-help photos-error":"photos-help"} onChange={e=>setFiles(Array.from(e.target.files||[]))}/><span id="photos-help" className={styles.small}>Up to five images, 5MB each. File contents are not read or uploaded.</span>{errors.photos&&<span id="photos-error" className={styles.error}>{errors.photos}</span>}{files.length>0&&<span>{files.length} test files retained locally</span>}</label><label className={styles.check}><input id="agreement" aria-describedby={errors.agreement?"agreement-error":undefined} type="checkbox" checked={agreement} aria-invalid={Boolean(errors.agreement)} onChange={e=>setAgreement(e.target.checked)}/><span>Preview statement: I confirm the information and photos are accurate to the best of my knowledge. This statement is not sent or recorded.</span></label>{errors.agreement&&<p id="agreement-error" className={styles.error}>{errors.agreement}</p>}</>}
 <button type="submit" className={styles.primary}>Review Preview {mode==="request"?"request":"listing"}</button><p className={styles.small}>No real submission takes place.</p></fieldset></form>}
 </section>;
}
