"use client";
import { useEffect,useRef,useState } from "react";
import { ProduceMedia } from "@/components/homepage/PreviewMedia";
import { marketplacePath,requestProducePath,marketplaceCategories,readMarketplace,marketplaceUrl,matchingListings,listingUrl,type MarketplaceFixture,type MarketplaceState } from "@/lib/marketplace-preview";
import styles from "@/styles/marketplace-preview.module.css";
export function MarketplacePreviewBrowse({items,initial}:{items:MarketplaceFixture[];initial:MarketplaceState}) {
 const [state,setState]=useState(initial),[query,setQuery]=useState(initial.q),[retry,setRetry]=useState(false),results=useRef<HTMLHeadingElement>(null),sheet=useRef<HTMLDialogElement>(null),filterButton=useRef<HTMLButtonElement>(null),[draftRegion,setDraftRegion]=useState(initial.region);
 useEffect(()=>{const restore=()=>{const next=readMarketplace(new URLSearchParams(location.search),items);setState(next);setQuery(next.q);};const canonical=marketplaceUrl(initial)+location.hash;if(location.pathname+location.search+location.hash!==canonical)history.replaceState(null,"",canonical);const id=location.hash.slice(1);if(id)requestAnimationFrame(()=>document.getElementById(id)?.focus());window.addEventListener("popstate",restore);return()=>window.removeEventListener("popstate",restore);},[items,initial]);
 function update(next:MarketplaceState,focus=false){const clean=readMarketplace(new URL(marketplaceUrl(next),location.origin).searchParams,items);history.pushState(null,"",marketplaceUrl(clean));setState(clean);if(next.q!==state.q)setQuery(clean.q);setRetry(false);if(focus)requestAnimationFrame(()=>results.current?.focus());}
 const matches=state.fixture?[]:matchingListings(items,state),pages=Math.max(1,Math.ceil(matches.length/12)),visible=matches.slice((state.page-1)*12,state.page*12),regions=Array.from(new Set(items.map(i=>i.region))).sort();
 return <section data-marketplace-browse><header className={styles.marketHeading}><p className={styles.small}>Marketplace</p><h1>Find what you&apos;re looking for.</h1><p>Explore produce and agricultural products from farmers and suppliers.</p></header>
  <div className={styles.discovery}><form onSubmit={e=>{e.preventDefault();update({...state,q:query,page:1},true);}}><label className={styles.searchLabel} htmlFor="market-search">Search Marketplace</label><div className={styles.search}><input id="market-search" type="search" value={query} maxLength={120} onChange={e=>setQuery(e.target.value)} placeholder="Search produce, product or location"/><button type="submit">Search</button></div></form></div>
  <div className={styles.secondaryFilters}><label className={styles.desktopRegion}>Region<select aria-label="Region" value={state.region} onChange={e=>update({...state,region:e.target.value,page:1})}><option value="">All regions</option>{regions.map(r=><option key={r}>{r}</option>)}</select></label><button type="button" ref={filterButton} className={styles.mobileFilters} aria-haspopup="dialog" onClick={()=>{setDraftRegion(state.region);sheet.current?.showModal();}}>Filters{state.region?" (1)":""}</button></div>
  <dialog className={styles.filterSheet} ref={sheet} onClose={()=>filterButton.current?.focus()} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close();}}} aria-labelledby="filter-title"><h2 id="filter-title">Filters</h2><p>Choose a region. Apply updates the results.</p><label htmlFor="filter-region">Region</label><select id="filter-region" value={draftRegion} onChange={e=>setDraftRegion(e.target.value)}><option value="">All regions</option>{regions.map(r=><option key={r}>{r}</option>)}</select><div className={styles.actions}><button type="button" onClick={()=>setDraftRegion("")}>Clear region</button><button type="button" onClick={()=>sheet.current?.close()}>Cancel</button><button className={styles.primary} type="button" onClick={()=>{update({...state,region:draftRegion,page:1});sheet.current?.close();}}>Apply filters</button></div></dialog>
  <div className={styles.categories} role="group" aria-label="Marketplace categories">{marketplaceCategories.map(c=><button key={c} type="button" aria-pressed={state.category===(c==="All"?"":c)} onClick={()=>update({...state,category:c==="All"?"":c,page:1})}>{c}</button>)}</div>
  {(state.q||state.category||state.region)&&<div className={styles.chips} aria-label="Active search and filters">{(["q","category","region"] as const).filter(k=>state[k]).map(k=><button key={k} type="button" onClick={()=>update({...state,[k]:"",page:1},true)} aria-label={`Clear ${k==="q"?"search":k}: ${state[k]}`}>{state[k]} ×</button>)}{(state.category||state.region)&&<button type="button" onClick={()=>update({...state,category:"",region:"",page:1},true)}>Clear filters</button>}</div>}
  <p className={styles.small}>Availability and listing details may need confirmation. <a href="/dev-preview/public/how-information-is-checked">How information is checked</a></p>
  <h2 id="market-results" tabIndex={-1} ref={results} aria-live="polite">{state.fixture==="unavailable"?"Listings unavailable":`${matches.length} Preview listings${matches.length?` · Showing ${(state.page-1)*12+1}–${Math.min(state.page*12,matches.length)}`:""}`}</h2>
  {state.fixture==="unavailable"?<div className={styles.state}><h3>Marketplace could not be loaded</h3><p>This deliberate Preview failure is different from having no listings.</p><button type="button" onClick={()=>setRetry(true)}>Retry</button>{retry&&<p role="status">The unavailable fixture remains unavailable. Your search and filters are preserved.</p>}<p><a href={requestProducePath}>Request Produce</a> · Local Preview only</p></div>:matches.length===0?<div className={styles.state}><h3>{state.fixture==="empty"?"No Preview listings available":"No listings match these choices"}</h3><p>This result describes synthetic fixtures, not real Ghanaian supply.</p><div className={styles.actions}><button type="button" onClick={()=>{update({...state,q:"",category:"",region:"",page:1},true);setQuery("");}}>Clear search and filters</button><a href={requestProducePath}>Request Produce</a></div></div>:<div className={styles.grid}>{visible.map(item=><article className={styles.card} key={item.id} id={`listing-${item.id}`} tabIndex={-1}><ProduceMedia image={item.image} category={item.subcategory}/><h3>{item.product}</h3><p>{item.region}</p><p>{item.farmerName||item.seller}</p><p className={styles.small}>Needs confirmation · synthetic listing</p><a aria-label={`View details: ${item.product}, ${item.title}`} href={listingUrl(item.id,marketplaceUrl(state)+`#listing-${item.id}`)}>View details</a></article>)}</div>}
  {pages>1&&<nav className={styles.pagination} aria-label="Marketplace pages"><button type="button" disabled={state.page===1} onClick={()=>update({...state,page:state.page-1},true)}>Previous</button>{Array.from({length:pages},(_,i)=><button key={i} type="button" aria-label={`Page ${i+1}`} aria-current={state.page===i+1?"page":undefined} onClick={()=>update({...state,page:i+1},true)}>{i+1}</button>)}<button type="button" disabled={state.page===pages} onClick={()=>update({...state,page:state.page+1},true)}>Next</button></nav>}
  <aside className={styles.sourcingFallback}><h2>Can’t find what you need?</h2><p>Tell us what you’re looking for and Ghana Growers can help coordinate the next step.</p><a href={requestProducePath}>Request Produce →</a><span className={styles.small}> Local Preview only</span></aside>
  <p className={styles.small}><a href="/dev-preview/list-a-product">List a Product</a> · Preview entry; no publication or sale.</p>
 </section>;
}
