"use client";
import {useState} from "react";
import {ProduceMedia} from "@/components/homepage/PreviewMedia";
import {listingUrl,sourcingUrl,type MarketplaceFixture} from "@/lib/marketplace-preview";
import styles from "@/styles/marketplace-preview.module.css";
export function MarketplacePreviewDetail({item,back,scenario}:{item:MarketplaceFixture;back:string;scenario:string}) {
 const [retry,setRetry]=useState(false),self=listingUrl(item.id,back);
 if(scenario==="unavailable"||scenario==="withdrawn")return <section data-marketplace-detail><a className={styles.back} href={back}>Back to Marketplace</a><h1>Listing unavailable</h1><div className={styles.state}><p>{scenario==="unavailable"?"This listing could not be loaded in the Preview scenario.":"This listing is not available for viewing."}</p>{scenario==="unavailable"&&<button type="button" onClick={()=>setRetry(true)}>Retry</button>}{retry&&<p role="status">The deliberate unavailable fixture remains unavailable. Your Marketplace choices are preserved.</p>}<a href="/dev-preview/request-produce">Request Produce</a></div></section>;
 return <article data-marketplace-detail><a className={styles.back} href={back}>Back to Marketplace</a><div className={styles.detailHero}><div className={styles.media}><ProduceMedia image={item.image} category={item.subcategory}/></div><header className={styles.panel}><p className={styles.small}>Synthetic Preview listing · not a real offer</p><h1>{item.title}</h1><p>{item.product} · {item.subcategory}</p><p>{item.region} · example location only</p><p><strong>Needs confirmation:</strong> current availability</p><p className={styles.small}>No real stock or availability review has occurred.</p><a className={`${styles.primary} ${styles.yellow}`} href={sourcingUrl("listing",item.id,back)}>Request Produce</a><p className={styles.small}>Local request demonstration. Nothing is sent; this is not an order.</p></header></div>
 <div className={styles.detailGrid}><div><section className={styles.panel}><h2>Listing information</h2><dl className={styles.definition}><dt>Product</dt><dd>{item.product} · synthetic label</dd><dt>Price</dt><dd>Unavailable</dd><dt>Quantity / stock</dt><dd>Unavailable</dd><dt>Quality / certification</dt><dd>Unavailable</dd><dt>Delivery / payment terms</dt><dd>Unavailable</dd></dl><p className={styles.small}>A visible listing does not confirm supply, quality, price or fulfilment.</p></section><section className={styles.panel}><h2>Information and evidence</h2>{scenario==="checked"?<><p><strong>Checked by Ghana Growers — fixture demonstration only</strong></p><p>Simulated scope: the product label. Source: a synthetic Preview record. Example date: <time dateTime="2026-09-08">8 September 2026</time>.</p><p>No real check has occurred. This is not evidence of seller identity, stock, quality or availability.</p></>:scenario==="under-review"?<><p><strong>Information under review — fixture demonstration</strong></p><p>Optional listing detail is withheld. No private review reason is displayed.</p></>:<><p><strong>Farmer-reported — fixture demonstration</strong></p><p>The product description demonstrates participant-supplied information. It was not received from a real seller or farmer.</p></>}<p><strong>Needs confirmation:</strong> availability and all commercial details.</p><a href="/dev-preview/public/how-information-is-checked">How information is checked</a></section></div><div><section className={styles.panel}><h2>Seller / farmer context</h2><p>{item.seller} · synthetic seller label</p>{item.farmerId?<><p>This fixture is associated with {item.farmerName} for navigation review only. It establishes no real seller/farmer relationship.</p><a className={styles.back} href={`/dev-preview/farmers/${item.farmerId}?listing=${encodeURIComponent(item.id)}&marketFrom=${encodeURIComponent(back)}`}>View farmer</a></>:<p>No farmer profile relationship is established for this fixture.</p>}</section><section className={styles.panel}><h2>Coordinated sourcing</h2><p>Ghana Growers helps clarify a sourcing need. A request does not guarantee a supplier, availability, quality, price, delivery or a match.</p><p>Ghana Growers is not the seller and does not take payment in this flow.</p><a href={sourcingUrl("listing",item.id,back)}>Request this product</a></section></div></div><nav className={styles.actions} aria-label="Listing support"><a href="/dev-preview/public/contact">Report incorrect listing information</a><a href={self}>Reset listing demonstration</a></nav><p className={styles.small}>Contact remains unavailable in Preview. No report is sent.</p></article>;
}
