"use client";
import { useEffect, useRef, useState } from "react";
import { blankDirectory, categories, directoryUrl, farmerDirectoryPath, farmerEntryPath, matchingFarmers, productValues, readDirectory, values, type DirectoryState, type FarmerFixture } from "@/lib/farmer-preview";
import styles from "@/styles/farmer-preview.module.css";
export function FarmerPreviewDirectory({items,initial}:{items:FarmerFixture[];initial:DirectoryState}) {
 const [state,setState]=useState(initial),[query,setQuery]=useState(initial.q),[draft,setDraft]=useState(initial),[open,setOpen]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null),rail=useRef<HTMLDivElement>(null),summary=useRef<HTMLHeadingElement>(null),search=useRef<HTMLInputElement>(null);
 const [notice,setNotice]=useState("");
 useEffect(()=>{const restore=()=>{const next=readDirectory(new URLSearchParams(location.search),items);setState(next);setQuery(next.q);};restore();const clean=directoryUrl(readDirectory(new URLSearchParams(location.search),items));if(location.pathname+location.search!==clean){history.replaceState(null,"",clean+location.hash);setNotice("Unsupported query choices were removed. The available filters are shown below.");}window.addEventListener("popstate",restore);if(location.hash)requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.focus());return()=>window.removeEventListener("popstate",restore);},[items]);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=previous;};},[open]);
 const matches=state.fixture==="empty"?[]:matchingFarmers(items,state),pages=Math.max(1,Math.ceil(matches.length/12)),current=Math.min(state.page,pages),shown=matches.slice((current-1)*12,current*12);
 const count=[state.region,state.district,state.product,state.farmType].filter(Boolean).length;
 function update(next:DirectoryState,focus?:string){const clean=readDirectory(new URLSearchParams(directoryUrl(next).split("?")[1]),items);history.pushState(null,"",directoryUrl(clean));setState(clean);if(next.q!==state.q)setQuery(clean.q);requestAnimationFrame(()=>{if(focus==="results"){summary.current?.focus();summary.current?.scrollIntoView({block:"start",behavior:"auto"});}else if(focus)document.getElementById(focus)?.focus();});}
 function close(){dialog.current?.close();setOpen(false);trigger.current?.focus();}
 function select(key:"region"|"district"|"product"|"farmType",value:string,mobile:boolean){const next={...(mobile?draft:state),[key]:value,page:1};if(key==="region")next.district="";if(mobile)setDraft(next);else update(next);}
 function fields(mobile:boolean){const s=mobile?draft:state;const controls=[{key:"region" as const,label:"Region",options:values(items,"region")},{key:"district" as const,label:"District",options:s.region?values(items.filter(i=>i.region===s.region),"district"):[]},{key:"product" as const,label:"Product",options:productValues(items)}];return <>{controls.map(f=><label key={f.key}>{f.label}<select aria-label={f.label} id={`${mobile?"sheet":"directory"}-${f.key}`} value={s[f.key]} disabled={f.key==="district"&&!s.region} onChange={e=>select(f.key,e.target.value,mobile)}><option value="">{f.key==="district"&&!s.region?"Choose region":"All"}</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>{f.key==="district"&&!s.region&&<span className={styles.fieldHint}>Choose a region first.</span>}</label>)}{mobile?<label>Farm Type<select aria-label="Farm Type" value={s.farmType} onChange={e=>select("farmType",e.target.value,true)}><option value="">All</option>{values(items,"farmType").map(o=><option key={o}>{o}</option>)}</select></label>:<details className={styles.more}><summary>More filters{state.farmType?" · 1 active":""}</summary><label>Farm Type<select aria-label="Farm Type" value={s.farmType} onChange={e=>select("farmType",e.target.value,false)}><option value="">All</option>{values(items,"farmType").map(o=><option key={o}>{o}</option>)}</select></label></details>}</>;}
 const chips=([['q','Search'],['region','Region'],['district','District'],['product','Product'],['farmType','Farm Type']] as const).filter(([key])=>state[key]);
 return <section aria-labelledby="directory-title" data-farmer-directory>
  <header className={styles.intro}><h1 id="directory-title">Find farmers</h1><p>Browse profiles by location and crops. Availability can change.</p></header>
  <div className={styles.discovery}>
   <form className={styles.search} onSubmit={e=>{e.preventDefault();update({...state,q:query,page:1});}}><label htmlFor="farmer-search">Search farmers</label><div><input ref={search} id="farmer-search" type="search" maxLength={120} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, crop or region"/><button type="submit">Search</button></div></form>
   <button ref={trigger} type="button" className={styles.filterTrigger} aria-haspopup="dialog" aria-expanded={open} aria-controls="farmer-filter-sheet" onClick={()=>{setDraft(state);setOpen(true);dialog.current?.showModal();}}>Filters · {count} active</button>
   <div className={styles.desktopFilters}>{fields(false)}</div>
  </div>
  <div className={styles.categories} aria-label="Crop categories"><button type="button" aria-label="Previous categories" onClick={()=>rail.current?.scrollBy({left:-170,behavior:"auto"})}>←</button><div ref={rail}>{categories.map(category=><button type="button" key={category} aria-pressed={state.product===(category==="All"?"":category)} onClick={()=>update({...state,product:category==="All"?"":category,page:1})}>{category}</button>)}</div><button type="button" aria-label="Next categories" onClick={()=>rail.current?.scrollBy({left:170,behavior:"auto"})}>→</button></div>
  <div className={styles.mobileRegion}><label>Region<select id="mobile-region" value={state.region} onChange={e=>select("region",e.target.value,false)}><option value="">All</option>{values(items,"region").map(o=><option key={o}>{o}</option>)}</select></label></div>
  <div className={styles.active} aria-label="Active search and filters">{chips.map(([key,label],i)=><button type="button" id={`remove-${key}`} key={key} aria-label={key==="q"?`Clear search: ${state.q}`:`Remove ${label} filter: ${state[key]}`} onClick={()=>{const next={...state,[key]:"",page:1};if(key==="region")next.district="";const remaining=chips.filter(([k])=>k!==key&&!(key==="region"&&k==="district"));const target=remaining[Math.min(i,remaining.length-1)];update(next,target?`remove-${target[0]}`:"farmer-results");}}>{label}: {state[key]} <span aria-hidden="true">×</span></button>)}{count>0&&<button type="button" onClick={()=>update({...blankDirectory,q:state.q,fixture:state.fixture},window.matchMedia("(max-width:40rem)").matches?"mobile-region":"directory-region")}>Clear filters</button>}</div>
  {notice&&<p role="status">{notice}</p>}
  <h2 ref={summary} id="farmer-results" tabIndex={-1} className={styles.resultsTitle} aria-live="polite">{state.fixture==="unavailable"?"Farmer profiles unavailable":matches.length?`${matches.length} ${matches.length===1?"farmer profile":"farmer profiles"} · Showing ${(current-1)*12+1}–${Math.min(current*12,matches.length)}`:state.fixture==="empty"?"No Preview profiles available":"No matching farmer profiles"}</h2>
  {state.fixture==="unavailable"?<div className={styles.state}><p>Profiles could not be loaded in this Preview scenario. Your search and filters are preserved.</p><button type="button" onClick={()=>{setNotice("Retry completed: this deliberate unavailable fixture remains unavailable. Your choices are preserved.");}}>Retry</button><p>Request Produce is unavailable in this Preview.</p></div>:!matches.length?<div className={styles.state}><p>{state.fixture==="empty"?"No farmer profiles are available in this Preview dataset. This does not describe real farmer coverage.":"No farmer profiles match these choices. Try another search or remove a filter."}</p><button type="button" onClick={()=>search.current?.focus()}>Adjust search</button><p>Request Produce is unavailable in this Preview.</p><a href={farmerEntryPath}>List Your Farm</a></div>:<><div className={styles.grid}>{shown.map(item=><article id={`card-${item.id}`} tabIndex={-1} key={item.id}><div className={styles.placeholder} aria-hidden="true">Photo not available</div><p className={styles.fixture}>Synthetic Preview profile</p><h3>{item.name}</h3><p>{item.district} · {item.region}</p><p>{item.products.slice(0,3).join(" · ")}{item.products.length>3?` · +${item.products.length-3} more`:""}</p><a className={styles.primary} href={`${farmerDirectoryPath}/${item.id}?from=${encodeURIComponent(directoryUrl(state)+"#card-"+item.id)}`} aria-label={`View ${item.name} profile`}>View profile</a></article>)}</div><nav className={styles.pagination} aria-label="Farmer result pages"><button type="button" disabled={current===1} onClick={()=>update({...state,page:current-1},"results")}>Previous</button>{Array.from({length:pages},(_,i)=><button type="button" key={i} aria-label={`Page ${i+1}`} aria-current={current===i+1?"page":undefined} onClick={()=>update({...state,page:i+1},"results")}>{i+1}</button>)}<button type="button" disabled={current===pages} onClick={()=>update({...state,page:current+1},"results")}>Next</button></nav></>}
  <p className={styles.support}><a href={farmerEntryPath}>List Your Farm</a> · Farmer entry is a Preview validation demonstration.</p>
  <dialog id="farmer-filter-sheet" ref={dialog} className={styles.sheet} aria-labelledby="filter-title" onKeyDown={e=>{if(e.key!=="Tab")return;const nodes=Array.from(e.currentTarget.querySelectorAll<HTMLElement>("button:not(:disabled), select:not(:disabled), input:not(:disabled), a[href]"));const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget)close();}}><div><header><h2 id="filter-title">Filter farmers</h2><button type="button" onClick={close}>Close</button></header><p>Choose filters, then apply. Changes are not applied when you close.</p><div className={styles.sheetFields}>{fields(true)}</div><footer><button type="button" onClick={()=>setDraft({...blankDirectory,q:state.q,fixture:state.fixture})}>Clear filters</button><button type="button" className={styles.primary} onClick={()=>{update({...draft,page:1});close();}}>Apply filters</button></footer></div></dialog>
 </section>;
}
