"use client";
import { useState } from "react";
import type { FarmerFixture } from "@/lib/farmer-preview";
import styles from "@/styles/farmer-preview.module.css";
export function FarmerPreviewProfile({farmer,back,scenario}:{farmer:FarmerFixture;back:string;scenario:string}) {
 const [expanded,setExpanded]=useState(false),[retry,setRetry]=useState(false);
 if(scenario==="unavailable"||scenario==="withdrawn")return <section data-farmer-profile><a href={back}>Back to farmers</a><h1>Profile unavailable</h1><div className={styles.state}><p>{scenario==="unavailable"?"This profile could not be loaded in the Preview scenario.":"This profile is not available for viewing."}</p>{scenario==="unavailable"&&<button type="button" onClick={()=>setRetry(true)}>Retry</button>}{retry&&<p role="status">This deliberate unavailable fixture remains unavailable. Return to your preserved directory choices.</p>}<a href={back}>Return to farmer results</a></div></section>;
 return <article data-farmer-profile><a className={styles.back} href={back}>Back to farmers</a>
  <header className={styles.profileHero}><div className={styles.profileIdentity}><p className={styles.fixture}>Synthetic Preview profile · not a real farmer</p><h1>{farmer.name}</h1><p>{farmer.district} · {farmer.region}</p><p>{farmer.farmType}</p><p className={styles.reviewDate}>Last reviewed: Unavailable — no real profile review has occurred.</p><p>This synthetic profile demonstrates location and crop information for founder review. It does not describe a real farm or current supply.</p><button type="button" className={styles.primary} disabled>Ask about supply</button><p className={styles.fixture}>Unavailable in this Preview. No sourcing request is sent.</p></div><div className={styles.placeholder} aria-hidden="true">Photo not available</div></header>
  <div className={styles.profileDetails}><div><section className={styles.panel}><h2>Crops / products</h2><p>Profile crops do not establish current availability.</p><ul className={styles.cropList}>{farmer.products.slice(0,expanded?undefined:6).map(product=><li key={product}>{product}</li>)}</ul>{farmer.products.length>6&&<button type="button" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?"Show fewer crops":`Show all ${farmer.products.length}`}</button>}</section>
  <section className={styles.panel}><h2>Information and evidence</h2>{scenario==="checked"?<><p><strong>Checked by Ghana Growers — fixture demonstration only</strong></p><p>Simulated scope: the crop labels shown above. Example source: a synthetic test record. Example check date: <time dateTime="2026-09-08">8 September 2026</time>.</p><p>No real operational check has occurred. This demonstration establishes no identity, availability, quality or transaction evidence.</p></>:scenario==="under-review"?<><p><strong>Information under review — fixture demonstration</strong></p><p>The optional profile detail is withheld in this scenario. No private reason or disputed claim is displayed.</p></>:<><p><strong>Farmer-reported — fixture demonstration</strong></p><p>The crop association illustrates participant-supplied information. These are synthetic labels, not statements received from a real farmer.</p></>}<p><strong>Needs confirmation:</strong> current supply is not established by this profile.</p><a href="/dev-preview/public/how-information-is-checked">How information is checked</a></section></div>
  <section className={styles.panel}><h2>No current Marketplace listings</h2><p>No current Marketplace listings are shown for this synthetic profile. This is not evidence about a real farmer’s availability.</p><button type="button" disabled>Request Produce</button><p className={styles.fixture}>Mediated sourcing and Marketplace destinations remain unavailable in this Preview. No guarantee of availability, matching, price, delivery or fulfilment.</p></section></div>
  <nav className={styles.profileEnd} aria-label="Profile support"><a href="/dev-preview/public/contact">Report incorrect profile information</a><a href={back}>Browse other farmers</a><p>Contact is not yet active in this Preview. No report is sent.</p></nav>
 </article>;
}
